# Generated by Django 4.2.5 on 2023-11-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_discount_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="information",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
