# Generated by Django 4.2.5 on 2023-11-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_product_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="concise",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
