# Generated by Django 4.2.7 on 2024-03-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_color_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=120, verbose_name='تنوع دسته بندی')),
                ('variation_value', models.CharField(max_length=120, verbose_name='مقدار تنوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='محصول')),
            ],
        ),
    ]
