# Generated by Django 4.2.7 on 2024-03-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'واریانت', 'verbose_name_plural': 'واریانت ها'},
        ),
    ]
