# Generated by Django 4.2.7 on 2024-03-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_variation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'رنگ'), ('size', 'size')], max_length=120, verbose_name='تنوع دسته بندی'),
        ),
    ]
