# Generated by Django 4.2.7 on 2024-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('رنگ', 'color'), ('size', 'size')], max_length=120, verbose_name='تنوع دسته بندی'),
        ),
    ]
