# Generated by Django 4.2.7 on 2024-08-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_product'),
        ('store', '0017_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='product',
            field=models.ManyToManyField(related_name='product_variations', to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='category.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variation',
            field=models.ManyToManyField(related_name='variation_products', to='store.variation'),
        ),
    ]
