# Generated by Django 4.2.7 on 2024-08-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_variation_product_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
    ]
