# Generated by Django 4.2.7 on 2024-08-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_variation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'رنگ'), ('size', 'اندازه')], max_length=120, verbose_name='تنوع دسته بندی'),
        ),
    ]
