# Generated by Django 4.2.7 on 2024-08-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
