# Generated by Django 4.2.7 on 2024-02-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'اکانت', 'verbose_name_plural': 'اکانت\u200cها'},
        ),
    ]
