# Generated by Django 4.2.7 on 2024-03-27 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=50, verbose_name=' ادرس تحویل')),
                ('profile_picture', models.ImageField(blank=True, upload_to='userprofile')),
                ('postal_code', models.CharField(max_length=50, verbose_name=' کد پستی')),
                ('state', models.CharField(max_length=50, verbose_name=' استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر ')),
                ('street', models.CharField(max_length=50, verbose_name='خیابان ')),
                ('tag', models.CharField(max_length=50, verbose_name=' پلاک')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
