# Generated by Django 4.2.7 on 2024-08-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_discount_alter_product_price'),
        ('category', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(related_name='product_category', to='store.product'),
        ),
    ]
