# Generated by Django 4.2.7 on 2024-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_variation_product'),
        ('category', '0005_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_category', to='store.product'),
        ),
    ]
