# Generated by Django 4.2.7 on 2024-08-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='device_info',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
