# Generated by Django 4.2.7 on 2024-09-05 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0004_coupon_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_alter_variation_variation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='شماره سفارش ')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=50, verbose_name=' نام خوانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name=' شماره تماس')),
                ('email', models.EmailField(max_length=50, verbose_name=' ایمیل')),
                ('address_line_1', models.CharField(max_length=50, verbose_name=' ادرس تحویل')),
                ('postal_code', models.CharField(max_length=50, verbose_name=' کد پستی')),
                ('state', models.CharField(max_length=50, verbose_name=' استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر ')),
                ('street', models.CharField(max_length=50, verbose_name='خیابان ')),
                ('tag', models.CharField(max_length=50, verbose_name=' پلاک')),
                ('order_total', models.IntegerField(verbose_name=' قیمت کل سفارشات')),
                ('tax', models.IntegerField(verbose_name=' مالیات')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('accepted', 'پذیرفته شده'), ('completed', 'کامل شده'), ('cancelled', 'لغو شده')], default='New', max_length=10, verbose_name=' وضعیت')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name=' ایپی')),
                ('is_ordered', models.BooleanField(default=False, verbose_name=' سفارش داده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=' زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'سفارش ',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='ایدی سفارش')),
                ('payment_method', models.CharField(max_length=100, verbose_name='روش پرداخت')),
                ('amount_paid', models.CharField(max_length=100, verbose_name='مقدار پرداختی')),
                ('status', models.CharField(max_length=100, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداختی',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name=' تعداد')),
                ('ordered', models.BooleanField(default=False, verbose_name=' سفارش داده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=' زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=' زمان بروزرسانی')),
                ('coupon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct_coupons', to='coupons.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='سفارش')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='پرداختی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('variation', models.ManyToManyField(blank=True, to='store.variation', verbose_name='واریانت')),
            ],
            options={
                'verbose_name': 'سفارش محصول',
                'verbose_name_plural': 'سفارش محصولات',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='پرداختی'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
