# Generated by Django 4.2.7 on 2024-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(default=0, verbose_name='مجموع کل'),
        ),
    ]
