# Generated by Django 4.2.7 on 2024-09-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_grand_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_ordered',
            new_name='ordered',
        ),
    ]
