# Generated by Django 4.2.7 on 2024-09-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_payment_remove_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'کامل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
