# Generated by Django 4.2.7 on 2024-09-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
