# Generated by Django 4.2.7 on 2024-09-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderproduct_payment_orderproduct_bank_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
    ]
